# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

matVecProd <- function(m, v) {
    .Call('_endogeneity_matVecProd', PACKAGE = 'endogeneity', m, v)
}

matVecProdSum <- function(m, ext, v, group) {
    .Call('_endogeneity_matVecProdSum', PACKAGE = 'endogeneity', m, ext, v, group)
}

matVecProdSumExt <- function(m, ext, ext2, v, group) {
    .Call('_endogeneity_matVecProdSumExt', PACKAGE = 'endogeneity', m, ext, ext2, v, group)
}

groupProd <- function(v, group) {
    .Call('_endogeneity_groupProd', PACKAGE = 'endogeneity', v, group)
}

groupSum <- function(v, group) {
    .Call('_endogeneity_groupSum', PACKAGE = 'endogeneity', v, group)
}

groupSumMat <- function(m, group) {
    .Call('_endogeneity_groupSumMat', PACKAGE = 'endogeneity', m, group)
}

